### ISSUE TITLE
Docker-compose validator service issue - workaround

### ISSUE THREAD

**Issue by aaron-bcw** [LimeChain/hedera-evm-bridge-validator#307]
When using the docker-compose setup the validator service crashes. 

I think this issue located in the docker-compose.yml file:
```
 volumes:
      - ./bridge.yml:/src/hedera-eth-bridge-validator/config/bridge.yml
      - ./node.yml:/src/hedera-eth-bridge-validator/config/node.yml
```

Volumes gets the bridge.yml and then adds it to the root directory. Since there is no bridge.yml or node.yml file in the root directory docker instead creates a empty directory.
This is known behavior make sure that files exist in both side (inside host machine and inside container).
If one of them does **not exist** then docker will **create a directory instead of a file**. 

When this happens the validator will crash.
So a work around is to remove the **empty directories** node.yml and bridge.yml created by docker in the root directory, and manually create the node.yml and bridge.yml **file** in the root directory. Then the validator service will work. 

I'm not sure what is the best solution to fix it.

If helpfull here is the crash log:
```
ERROR: for hedera-evm-bridge-validator_validator_1  Cannot start service validator: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/noctilux/bcw/hedera-evm-bridge-validator/node.yml" to rootfs at "/src/hedera-eth-bridge-validator/config/node.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for validator  Cannot start service validator: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: rootfs_linux.go:76: mounting "/home/noctilux/bcw/hedera-evm-bridge-validator/node.yml" to rootfs at "/src/hedera-eth-bridge-validator/config/node.yml" caused: mount through procfd: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

**Comment by failfmi** [comment]
Thank you for opening this issue. It has been [resolved](https://github.com/LimeChain/hedera-evm-bridge-validator/pull/310).
