### ISSUE TITLE
Resolve Mirror node timeout

### ISSUE THREAD

**Issue by Daniel-K-Ivanov** [LimeChain/hedera-evm-bridge-validator#59]
Watcher connections to the mirror node are dropped after several minutes.
Verify that connections are dropped only if there is more than 1 connection to the mirror node (in the 3 validator network). If the problem occurs only in the 3 node validator network we can dismiss the issue.

If the problem occurs in a standalone node as-well, the issue must be resolved.

How to reproduce:
- Start a signal node and wait for ~10 minutes. See in the logs whether there are any issues with a timed out connections.
- Start the three-node validator docker-compose. Wait a couple of minutes and notice the timeout errors.

**Comment by Daniel-K-Ivanov** [comment]
cannot reproduce

**Comment by failfmi** [comment]
Cannot reproduce
